### ISSUE TITLE
I have java.nio.file.NoSuchFileException

### ISSUE THREAD

**Issue by AlexandrPutenikhin** [lwjglgamedev/lwjglbook#1]
I am on chapter 03
I am using intellij idea

**Comment by lwjglgamedev** [comment]
I guess, you are getting this exception while reading the shaders. Please check the working diretcory whre you are executing the sample. If you open the parent diretcory (the one that contains all the chapters projects) you will need to establish the working directory for each of the chapters. This is explained in chapter 1. If not, please provide full exception stack and try to get the full path to the file to check where it is lloking for it.

**Comment by lwjglgamedev** [comment]
Since I've received no response, I suppose you have solved your issues. Therefore, I'm closing the issue. If this is not the case, please feel free to re-open it.
