### ISSUE TITLE
[Chapter 10] Maven cannot resolve some symbols in pom.xml

### ISSUE THREAD

**Issue by Domochevsky** [lwjglgamedev/lwjglbook#10]
At the start of the chapter new dependencies are added to the pom.xml:

```
<dependency>
    <groupId>io.github.spair</groupId>
    <artifactId>imgui-java-binding</artifactId>
    <version>${imgui-java.version}</version>
</dependency>

<dependency>
    <groupId>io.github.spair</groupId>
    <artifactId>imgui-java-${native.target}</artifactId>
    <version>${imgui-java.version}</version>
    <scope>runtime</scope>
</dependency>
```

However, neither `${imgui-java.version}` resolves to anything, nor `${native.target}` or `${imgui-java.version}`.

As a result, Maven complains that it cannot find `io.github.spair:imgui-java-binding:jar:${imgui-java.version}` in Central https://repo.maven.apache.org/maven2

Are these placeholder values referencing something I should have added somewhere? I checked the original pom.xml, and I cannot see any definitons in there either.

**Comment by lwjglgamedev** [comment]
These variables are defined in the parent pom. If you have downloaded it it should compile.

**Comment by Domochevsky** [comment]
Parent pom... which one is that? I don't see one in the project structure. (I did not download it, no. I followed the instructions.)
It doesn't seem to get mentioned in the gitbook either, otherwise I'd have stumbled upon it, I suspect.

**Comment by lwjglgamedev** [comment]
Ok, I see now. You should download the whole repo. You can download it as a zip file or clone it: `git clone https://github.com/lwjglgamedev/lwjglbook.git`.

After that, in the root folder that contains all the chapter examples, you wil see a `pom.xml` file. This is the parent POM file, which conatins certain properties used by all the chapters.

**Comment by Domochevsky** [comment]
Ah, I see. That is good to know. And probably something you should at least mention and explain in the first chapter. It seems kinda important. :)

If I were to download just that file, where would I place it? Do I merge it with my existing pom.xml? Put it somewhere else? Reference it somewhere?

**Comment by lwjglgamedev** [comment]
I'll add more explanation about thism however, as it is explained in the booke, it does not intended to be a maven tutorial. When you clone the repo you will get all the folders and subfolder you need, there is no need to change anything. In any case the parent `pom.xml` is in the root foilder of the repo, while each chapter has its own project `pom.xml`. If you clone the repo you will see the structure. No need to merge, each chapter `pom.xml` refers to the parent `pom.xml`.

**Comment by lwjglgamedev** [comment]
Added more description to the first chapter.
