### ISSUE TITLE
CH28: Game rendering tiny in window

### ISSUE THREAD

**Issue by cleverpanda** [lwjglgamedev/lwjglbook#103]
I imported the project into IntelliJ and when I run, the game is only rendered tiny in the bottom left corner.
![image](https://user-images.githubusercontent.com/2975515/152268697-655ea757-2f65-45f1-80e3-e16c6f1a0281.png)

If I minimize the window, it resizes the window to that tiny size.
If I then resize the entire window to be larger, the game seems to be rendered  super zoomed-in
![image](https://user-images.githubusercontent.com/2975515/152268486-b0277b3f-dee7-43e0-9bda-a6e1e958005f.png)

**Comment by lwjglgamedev** [comment]
Ok, I will try to fix it on the weeked. It seems that the buffers do not take account properly of resizing. Thanks for reporting.

**Comment by lwjglgamedev** [comment]
Fixed. It seems that the behaviour of GLFW has changed in latest versions. In any case, I was doing quite a silly thing by setting a size 100x100 when maximizing. Now I get the surface dimensions. Much better approach.
