### ISSUE TITLE
Error running  chapter 21 and 22

### ISSUE THREAD

**Issue by MauOcon** [lwjglgamedev/lwjglbook#11]
Error compiling Shader code: 0:167(2): error: `return' with wrong type int, in function `calcShadow' returning float

Solution:
In scene_fragment.fs, in calcShadow change return types from 1 to 1.0

**Comment by lwjglgamedev** [comment]
I will check this as soon as possible, Bythway, which is your OS and GPU ? In the ones that I've tested this error does not occur.

**Comment by MauOcon** [comment]
Hi

My OS is Ubuntu 16.04 64 bit and my video card is Intel HD Graphics 4000

**Comment by lwjglgamedev** [comment]
Thanks for the info and for pointing the issue.

I've just uploaded a fix for that. Please close the issue if it works for you.
