### ISSUE TITLE
Chapter 13: m30, m31, m32

### ISSUE THREAD

**Issue by olliejohnson** [lwjglgamedev/lwjglbook#112]
The lines
`viewMatrix.m30(0);
 viewMatrix.m31(0);
 viewMatrix.m32(0);`

are giving errors

**Comment by lwjglgamedev** [comment]
What are errors are you getting? It compiles ok (these are proper methods of Matrix4f class).

**Comment by olliejohnson** [comment]
The error I am getting is
java: cannot find symbol
  symbol:   method m30(int)
  location: variable viewMatrix of type org.joml.Matrix4f
