### ISSUE TITLE
PointLight problem. 

### ISSUE THREAD

**Issue by DomagojRatko** [lwjglgamedev/lwjglbook#115]
Found problem when using point light with shadows. Example picture.
![1](https://user-images.githubusercontent.com/62218857/183988824-2c589079-c077-4f36-aedb-239d1bd14092.png)

Here is example using point light without shadows.  
![2](https://user-images.githubusercontent.com/62218857/183989148-3a9b203c-1b13-4846-8034-2a1afb864afe.png)
 
Also example of using shadows without point light.
![11](https://user-images.githubusercontent.com/62218857/183989985-c43925af-5e64-4e3b-bc37-50b9e763192f.png)

So based on this I assume that problem would be somewhere with point light and how it works.
Any ides how could I try to fix this issue?

**Comment by lwjglgamedev** [comment]
Hi, I'm currently refactoring the book, so either you cen retest this when the work is done or I can give you early access to the new version.

**Comment by DomagojRatko** [comment]
I will retest this when you finish refactoring the book. I'm not in hurry to fix this. If I figure out before that what was a issue, will make sure I share solution. 
Also great work with book, appreciate the effort 👍

**Comment by lwjglgamedev** [comment]
Thanks, I will close this issue and I have added you to the new repo just for you to check if you want.
