### ISSUE TITLE
Typo in book.

### ISSUE THREAD

**Issue by dragonslayer0531** [lwjglgamedev/lwjglbook#12]
This isn't really an issue, but I figured I would let you know.  On page 8, code is spelled "codee" below the figure.  I will try to post updates as I read through so you can fix issues such as that.

**Comment by lwjglgamedev** [comment]
Many thanks, I really appreciate that. I'm having some busier days now but I will try to fix the typos as soon as I can.

**Comment by dragonslayer0531** [comment]
If you would like, I can go through and fix typos and grammatical errors as
I come across them.  That would let you focus more on the book and other
things that come up.  I completely understand the being busy part.

**Comment by lwjglgamedev** [comment]
That would be certainly great. But, first I need to figure out how can you submit pull request to the git repository that gitbook uses. I will check this. In the meantime, maybe you can annotate (in a document or whatever) the typos and send me batches.

Many thanks

**Comment by lwjglgamedev** [comment]
Source code for the book is now in github. I will close this isse.
