### ISSUE TITLE
[CHAPTER 14] skybox.vert layout(location=2) textCoord should be 4 instead of 2 in order to test normal mapping in the same scene.

### ISSUE THREAD

**Issue by andrlzpt** [lwjglgamedev/lwjglbook#14]
The Normal Mapping instructions change the location of the texture VBO to index 4.
The skybox.vert textCoord reference location should be changed to 4, too, if one wanted to use skybox and the normal mapping setup as presented in the chapter.

**Comment by lwjglgamedev** [comment]
Thanks !
