### ISSUE TITLE
Chapter 7 question

### ISSUE THREAD

**Issue by mudlee** [lwjglgamedev/lwjglbook#15]
In chapter7, at the beginning (creating cube), v6 has the coordinate -0.5f, -0.5f, -0.5f. Why the X coordinate is negative? 
I tried to create coordinates by myself and -0.5f, -0.5f, -0.5f is the coordinate of the v7 regarding to the 3D image at the start in the chapter.

I just went through the triangles, and I see that the right face's triangle is 3, 2, 7, which makes no sense, so I think the image is the bad guy here, v6 and v7 is switched(?).

**Comment by lwjglgamedev** [comment]
Many thanks for pointing this. I will check this as soon as possible.

**Comment by lwjglgamedev** [comment]
I've just uploaded a corrected image for the book.

Good catch ! Thanks for reporting this issue.

**Comment by mudlee** [comment]
Cool!
