### ISSUE TITLE
[CHAPTER 15] typo in scene.vert initTangent set twice, second time should be initBitangent

### ISSUE THREAD

**Issue by andrlzpt** [lwjglgamedev/lwjglbook#15]
This is the code for the scene.vert in the chapter 15: 
```
            vec4 tmpTangent = bonesMatrices[boneIndex] * vec4(tangent, 0.0);
            initTangent += weight * tmpTangent;

            vec4 tmpBitangent = bonesMatrices[boneIndex] * vec4(bitangent, 0.0);
            initTangent += weight * tmpBitangent;  // this should be initBitangent += ... Right?
```
I believe the initTangent is being set twice, and it should be replacecd by initBitangent
...
Another question about the chapter (more a question than an issue, really): 
has it been tested for animations in the gltf format?
 I'm able to load the animation data, and logs for the nextFrame() calls return sucessfully, but the animation never plays. 
Thanks in advance.

**Comment by lwjglgamedev** [comment]
Yes, it seems a typo. I will try to upload a fix this weekend.

Regarding your GTLF question, it should work the same way. I can try to test with some example. However, the code is quite similar to the one used in the vulkan book, which I've tested with GTLF models (you have  a working example  [here](https://github.com/lwjglgamedev/vulkanbook/tree/master/booksamples/appendix-02), although this uses compute shaders, the way to process animations should be more or less the same).

**Comment by andrlzpt** [comment]
About the gltf, YES! It works perfectly! The way I was exporting was the problem! Thanks so much!

**Comment by lwjglgamedev** [comment]
Fixed. Thanks for reporting. Keep on reviewing !
