### ISSUE TITLE
Question about spotlight reflection handling

### ISSUE THREAD

**Issue by mudlee** [lwjglgamedev/lwjglbook#16]
Hi!

I'm just wondering that in the tutorial, directional- and pointligths are handling the material reflectivity in the fragment shader as I expected. My question is: why the spotlight calculation does not? So if I light an object with only a spotlight, it does not matter how reflective it is?

Thanks. 

BTW, this tutorial is a must for people who start learning lwjgl. Cannot say enough, thank you guy(s)! Well written, well done material!

**Comment by mudlee** [comment]
OK, I'm closing this, after an hour of checking the code I sent this, then - of course - I've found the line I missed in the calcSpotLight method: 
`colour = calcPointLight(light.pl, position, normal);`

**Comment by lwjglgamedev** [comment]
Ok, glad to hear that.
