### ISSUE TITLE
NullPointerException at Scanner constructor

### ISSUE THREAD

**Issue by espacotempo** [lwjglgamedev/lwjglbook#19]
Hi, I'm facing a NullPointerException in the Utils.java line 11 (chapter 4 forward), when it try to instantiate the Scanner.
The file of the string 'fileName'  is ok.
LOG:
vertex.vs is a true file (my print)
java.lang.NullPointerException: source
	at java.util.Objects.requireNonNull(Objects.java:228)
	at java.util.Scanner.<init>(Scanner.java:578)
	at org.lwjglb.engine.Utils.loadResource(Utils.java:11)
	at org.lwjglb.game.Renderer.init(Renderer.java:26)
	at org.lwjglb.game.DummyGame.init(DummyGame.java:22)
	at org.lwjglb.engine.GameEngine.init(GameEngine.java:50)
	at org.lwjglb.engine.GameEngine.run(GameEngine.java:38)
	at java.lang.Thread.run(Thread.java:745)

**Comment by lwjglgamedev** [comment]
I will check this as soon as possible.

**Comment by espacotempo** [comment]
I'm trying to fix it. But nothing for now.
Thanks

**Comment by lwjglgamedev** [comment]
I've just checked it and I'm able to execute it with no problem. The exception you get is because the InputStream that points to the file is null. That mens that the file cannot be loaded from the CLASSPATH. Are you executing the sample inside Netbens? If not, please tell me which IDE are you using.

In any case, try to add to the CLASSPATH the resources folder.

**Comment by espacotempo** [comment]
I'm executing the sample inside Eclipse.

**Comment by espacotempo** [comment]
I have added the resources folder to the class folder and it worked.
Thank you very much.

**Comment by H4rryR** [comment]
Hi, I am also getting a **NullPointerException** but am not entirely sure why. 

- I have added the resources folder to the CLASSPATH..
- I am using Eclipse Neon.
- I can see that gameItems is null but still trying to figure out why this is.

**Error log:**
java.lang.NullPointerException
	at com.harryradford.game.DummyGame.cleanup(DummyGame.java:194)
	at com.harryradford.engine.GameEngine.cleanup(GameEngine.java:77)
	at com.harryradford.engine.GameEngine.run(GameEngine.java:41)
	at java.lang.Thread.run(Thread.java:748)
	at com.harryradford.engine.GameEngine.start(GameEngine.java:27)
	at com.harryradford.game.Main.main(Main.java:13)

**Zipped project:**
[Ch7lwjglbook.zip](https://github.com/lwjglgamedev/lwjglbook/files/1052550/Ch7lwjglbook.zip)

**Comment by schmalexandre** [comment]
Which class folder did you add the resources folder to? I'm having the same issue.

**Comment by lwjglgamedev** [comment]
The folder named "resources".

**Comment by AndyKrause95** [comment]
Same issue... where exactly do I put the resource folder within Eclipse? Can't really get this figured out. Someone walk me through the steps please

**Comment by lwjglgamedev** [comment]
The easy way, just import the samples for each chapter as a maven project. For instance, for chapter28. In eclipse:
- Select File->Import...
- In the dialog box, select the "Maven" folder and select the "Existing Maven Projects" option.
- Then, in the new dialog that opens, in the Root path, select the path to the chapter28. Select the folder, eclipse will detect the pom.xml for you.
- You should see in the "Projects" panel, that the pom.xml entry is shown. In case it is not marked, check it.
- Just click "Finish", and that's all.

If you still experience problems, please let me know.
