### ISSUE TITLE
Audio problems in Chapter 16

### ISSUE THREAD

**Issue by brickwall2900** [lwjglgamedev/lwjglbook#2]
Audio stops halfway when playing a long audio file.
I tested this with a 1 minute stereo song and it only played 30 seconds of it.

I have looked around the problem and found a solution to it:
In the `SoundBuffer` class and in the `readVorbis` method, instead of passing in `lengthSamples` to allocate the result, we need to pass in `lengthSamples` multiplied by the `channels`.

```java
int channels = info.channels();
int lengthSamples = stb_vorbis_stream_length_in_samples(decoder);
ShortBuffer result = MemoryUtil.memAllocShort(lengthSamples * channels);
```

**Comment by lwjglgamedev** [comment]
You are absolutely right. Thank you for reporting. I've already uploaded a fix.
