### ISSUE TITLE
ENHANCEMENT:  Chapter Recommendations

### ISSUE THREAD

**Issue by nickclark2016** [lwjglgamedev/lwjglbook#20]
As I have been reading through the book, I have a few ideas for future chapters that you can add (solely graphics).
- Anti-Aliasing (SMAA, MSAA, FXAA, etc.)
- Frustum Culling
- Occlusion Culling
I would also recommend looking back at your shaders.  After you attach a shader to a program, you can delete it, as it will delete the plain-text version of the shader from the GPU, while leaving the compiled version active.

**Comment by lwjglgamedev** [comment]
Many thanks for your suggestions.

**Comment by dragonslayer0531** [comment]
No problem!

**Comment by nickclark2016** [comment]
I have something that might be of interest to you.  I have a debugging utility for OpenGL and GLFW.  I don't mind if you use this in the future!  I enjoy what you are doing.  Please keep up the good work!

https://github.com/nickclark2016/Luminos/blob/master/src/tk/luminos/DebugUtil.java

**Comment by lwjglgamedev** [comment]
Very interesting tool. In fact, this something that can be very useful. I will have a look at it.

**Comment by nickclark2016** [comment]
Another recommendation for you:

When processing things for rendering, use Java 8's streams.  When I submitted everything to a map for rendering, I found that it was more efficient to use parallel streams to add each entity to a map.  This way, when entities are submitted, less time is spent on computing with respect to the rendering!
