### ISSUE TITLE
Maybe use Matrix4f.unprojectRay/unprojectInvRay() in chapter 23

### ISSUE THREAD

**Issue by httpdigest** [lwjglgamedev/lwjglbook#21]
Since version 1.8.0 (released on June 3, 2016) JOML's Matrix4f class can unproject from window coordinates via `unprojectRay()` and `unprojectInvRay()`.
The `MouseBoxSelectionDetector.selectGameItem()` can be simplified then.

**Comment by lwjglgamedev** [comment]
I can mention that in the book, but maybe it's a good idea to see how the process is done.
