### ISSUE TITLE
Terrain Issue

### ISSUE THREAD

**Issue by TomBlakley** [lwjglgamedev/lwjglbook#27]
Hello, I've tried creating a Terrain on Chapter 26, And Chapter 25. It works fine, But the Terrain is vanishing when it shouldn't, Am I doing something wrong?

I added this into the init method in DummyGame class

float terrainScale = 10;
        //int terrainSize = 3;
        int terrainSize = 3;
        float minY = -0.1f;
        float maxY = 0.1f;
        int textInc = 40;
        terrain = new Terrain(terrainSize, terrainScale, minY, maxY, "/textures/heightmap.png", "/textures/terrain.png", textInc);
        scene.setGameItems(terrain.getGameItems());

**Comment by TomBlakley** [comment]
Just tried with Chapter 24, And it works perfectly. Must be something to do with Frustum Culling

**Comment by lwjglgamedev** [comment]
Yes, I also think is related to frustum culling. I will add two changes:
- A flag to disable frustum culling globally.
- A flag to disable frustum culling per game item.

Thanks fr pointing that. I will try to make these changes in the next days.

**Comment by TomBlakley** [comment]
Thanks buddy :) This really helps
