### ISSUE TITLE
Minor render issue

### ISSUE THREAD

**Issue by rocammo** [lwjglgamedev/lwjglbook#29]
It would be better that in the package `main.java.org.lwjglb.engine`, the 'protected void render()' method of the class GameEngine
`protected void render() {`
`···· gameLogic.render(window);`
`···· window.update();`
`}`
, looks like this:
`protected void render() {`
`···· glfwPollEvents();`
`···· gameLogic.render(window);`
`···· glfwSwapBuffers(window);`
`}`
If not, there may be render problems.

Regards.
P.S. An outstanding book!

**Comment by lwjglgamedev** [comment]
Thanks for your comment !

I see your point, but maybe it's even better to poll the events in the GameEngine init method, befor the input processing is delegated. Do you agree?

**Comment by rocammo** [comment]
In principle, there are no problems with polling the events in the GameEngine init method. In fact, as you say maybe it's even better. Your GameEngine class implements Runnable, and in the run() method it's included the init method. In this way, the input processing will be delegated after the init method.

So... yeah, it's PERFECT! Well looked! ;-)

**Comment by lwjglgamedev** [comment]
Ok, I will make the changes when I have more spare time. Since I'm not using callbcks for processing key events, it's not urgent.

Thanks for pointing this !
