### ISSUE TITLE
Example code license?

### ISSUE THREAD

**Issue by jjYBdx4IL** [lwjglgamedev/lwjglbook#35]
Could you please clarify under which terms readers are allowed to use the example code in this repository?

TY!

**Comment by lwjglgamedev** [comment]
I gues that it should be the same license as the book: https://creativecommons.org/licenses/by-sa/4.0/

But I'm open to cange it if some one points any good reason.

**Comment by jjYBdx4IL** [comment]
I'd like to use the examples as a start for a game. To be able to do so the ShareAlike feature certainly does not help. The usual license is Apache v2, which is what I'd recommend if you want people to get the most out of your book. You could even fill an existing gap that way: provide a solution that is between JME3 and lwjgl3, i.e. a starting point without having to use 'obfuscating' frameworks and at the same time having a decent book providing the introduction.

**Comment by lwjglgamedev** [comment]
Ok,

My interest on this can be summarize as follows, you can do whatever you want with the source code of the samples as long as you give proper credit. If you want to use it to build up something onto it, it's fine for me. I'll have a look at Apache v2. maybe LGPL can also another option ?

Regards.

**Comment by jjYBdx4IL** [comment]
The Apache license has the special feature of automatically revoking any license grants in case the license user files any patent related litigation, even if not related to his use of the specific code. It's probably the most commonly used one in open source projects that actually are being used :-). 

A similar one is probably https://creativecommons.org/licenses/by/4.0/ which simply removes the ShareAlike part. The ShareAlike resembles more the restrictive GPL licenses.

**Comment by lwjglgamedev** [comment]
Ok, I've just clarified the license for source code, and set it to Apache v2. This way you have more freedom to do whatever projects you want with it.

**Comment by jjYBdx4IL** [comment]
Cool. TY!
