### ISSUE TITLE
Crashing on Chapter 2 unexpectedly? 

### ISSUE THREAD

**Issue by BlakeBarnes00** [lwjglgamedev/lwjglbook#40]
I am fairly new to using LWJGL, and I keep getting this error. From what I can tell from reading under the THREAD section in the log, it seems to crash on Thread.run()

Here is the log file IntelliJ spits out at me: [hs_err_pid18639.log ](https://gist.github.com/BlakeBarnes00/fe7508820a735b39b2e3477aeb5651af)

**Comment by httpdigest** [comment]
This is _not_ the code from Chapter 1. You modified it apparently to run on its own thread.
See the answer to your issue posted on the lwjgl3 repo: https://github.com/LWJGL/lwjgl3/issues/332

**Comment by BlakeBarnes00** [comment]
```java
this.windowHandle = glfwCreateWindow(this.width, this.height, this.title, 1, 0);
```
Changing the above line of code to: 
```java
this.windowHandle = glfwCreateWindow(this.width, this.height, this.title, 0, 0);
```

fixes the issue. @sriharshachilakapati should get all the credit over on https://github.com/LWJGL/lwjgl3/issues/332
