### ISSUE TITLE
GLFW_VERSION_UNAVAILABLE error

### ISSUE THREAD

**Issue by schmalexandre** [lwjglgamedev/lwjglbook#41]
I receive this error when I try to run Chapter 2 of your code:

Building game-c02 1.0

--- exec-maven-plugin:1.2.1:exec (default-cli) @ game-c02 ---
[LWJGL] GLFW_VERSION_UNAVAILABLE error
	Description : WGL: OpenGL profile requested but WGL_ARB_create_context_profile is unavailable
	Stacktrace  :
		org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1361)
		org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1521)
		org.lwjglb.engine.Window.init(Window.java:53)
		org.lwjglb.engine.GameEngine.init(GameEngine.java:44)
		org.lwjglb.engine.GameEngine.run(GameEngine.java:36)
		java.lang.Thread.run(Thread.java:748)
java.lang.RuntimeException: Failed to create the GLFW window
	at org.lwjglb.engine.Window.init(Window.java:55)
	at org.lwjglb.engine.GameEngine.init(GameEngine.java:44)
	at org.lwjglb.engine.GameEngine.run(GameEngine.java:36)
	at java.lang.Thread.run(Thread.java:748)

I am using LWJGL 3.1.2 build 29, on NetBeans IDE 8.2. The only change I made to the code is that I commented out the glfwWindowHints code in the Window class file.

**Comment by lwjglgamedev** [comment]
It seems that your graphics card does not support that version of OpenGL.
