### ISSUE TITLE
New OpenGL features

### ISSUE THREAD

**Issue by mudlee** [lwjglgamedev/lwjglbook#44]
Hi, just a comment. I've started to read the [OpenGL red book](https://www.amazon.co.uk/OpenGL-Programming-Guide-Official-Learning/dp/0134495497/), and there are a lot of new stuff people can use, but none of the existing tutorials cover.

For example:
- Direct State Access - from 4.5
- Separated shaders with pipelines - from 4.1

Here is my repo where I use these, feel free to use it to update your tutorials: [https://github.com/mudlee/intermetto2D](https://github.com/mudlee/intermetto2D)

I commit only, when everything is running fine. BTW, it will be (ever?) a 2D platformer, nothing special :)

**Comment by lwjglgamedev** [comment]
Hi,

Thanks for the suggestions. I will have a look at it. It's been a long time since I added new chapters, due to lack of spare time. In any case, I was also thinking in writing a tutorial about deferred shading.

Best regards.
