### ISSUE TITLE
Attach weapon to model 

### ISSUE THREAD

**Issue by RUSshy** [lwjglgamedev/lwjglbook#48]
Hi

I wonder how to do that ?

Thanks for this amazing book, it helped me a lot!

**Comment by lwjglgamedev** [comment]
Here you have some options:

[https://gamedev.stackexchange.com/questions/136639/how-to-handle-equipment-on-a-3d-animated-character](https://gamedev.stackexchange.com/questions/136639/how-to-handle-equipment-on-a-3d-animated-character)
