### ISSUE TITLE
Idea: Animation improvements

### ISSUE THREAD

**Issue by RUSshy** [lwjglgamedev/lwjglbook#52]
Hi,

Is it possible to cover these following subjects ?

- Animation Interpolation
- Speed adjustement

Ty!

**Comment by lwjglgamedev** [comment]
I do not have any planned updates on animation. Anyway you have a good tutorial on that subject here: http://ogldev.atspace.co.uk/www/tutorial38/tutorial38.html

**Comment by RUSshy** [comment]
Thanks this will help me!
