### ISSUE TITLE
Chapter 8 - mouseInput.input() polled too often (or not checked often enough)

### ISSUE THREAD

**Issue by Domochevsky** [lwjglgamedev/lwjglbook#6]
**Describe the bug**
1. Chapter 8 is about camera movement. `MouseInput` gets polled via `window.pollEvents()` in `Engine.run()`, line 51. This happens as fast as the program can run.
2. However, polling clears the previous mouse position delta, then grabs a new mouse X/Y delta.
3. Input is checked in line 58 of Engine.run(), whenever a display frame occurs, so it's happening at a rate of let's say 60 times per second.
4. The problem: The mouse cursor position is polled and cleared much more often in line 51 than it is applied  in line 58. As a result mouse movement is basically ignored unless you happen to catch a mouse delta in the frame it checks for it. (then it stutters into a slightly different position.)

A potential solution here is to not clear the mouse vector until it is polled (and adding to it in the meantime). 
Or alternatively moving `mouseInput.input();` out of `Window.pollEvents()` and into `Engine.run()` between line 57 and 58, so it is polled and used in the same frame.

**Comment by lwjglgamedev** [comment]
Hi, thanks for reporting.

You are absolutely right. I cannot recall why I mixed GLFW polling and updating mouse displacements. The best solution in my opinion is the last one you suggest. I will probably create a new method to polling the mouse status and invoke it prior to handling input. I will update this as soon as I have some spare time.

**Comment by lwjglgamedev** [comment]
Fixed. If you see that there is still something missing, just reopen. Thanks!
