### ISSUE TITLE
Do we have to give credit/can we use it freely?

### ISSUE THREAD

**Issue by Pichuminer** [lwjglgamedev/lwjglbook#66]
I love your book so much! I'm still reading it and studying it. Yet, I'm still wondering if we have to give you credit/take the code without needing to give credit towards you. Either answer, I'd still give you credit in any way possible inspiring me to start game development. <3

**Comment by lwjglgamedev** [comment]
Thanks for your words. You should give propoer credit if you can. In any case If you can't, for whatever reason, it is also ok ;). The code is for education purposes-
