### ISSUE TITLE
Issues related with lights and memory leak

### ISSUE THREAD

**Issue by AndreiDarashkou** [lwjglgamedev/lwjglbook#7]
First of all thank you for your book and source code. It's great work and I'm grateful you for this. :)
Unfortunately I discovered some issues:
1) After starting application in memory creates two processes. But after closing window with game there is one process still lives.
2) Point light doesn't work correctly. I use code source from 18.2 chapter and set only ambient and point lights. But only half of scene is under light.
3) And why in Transformation class in method "updateGenericViewMatrix" - we don't rotate over Z position? If I set directional light in position(1,0,0) shadow will not be correctly displayed.
![light issue](https://cloud.githubusercontent.com/assets/14922123/16142617/7e98e6bc-346f-11e6-8962-6076d33de18f.png)
![memory issue](https://cloud.githubusercontent.com/assets/14922123/16142618/7e995f3e-346f-11e6-99b9-b9d9e44fc3ed.png)

**Comment by lwjglgamedev** [comment]
Hi Andrei, 

Thanks for your comments. Regarding your questions:

1) I am not able to reproduce that issue. Some questions:
    1.a) Are you sure that this JVM is not created by other program?
    1.b) In my case, I use Netbeans. When I launch the examples, it creates two JVM process. The first one is for maven, which then launches the second one. But when I close the the window, both process die.
    1.c) I guess that you are using Windows 10. Can you confirm this? If so, I will try to test it in that environment.

2) I think that the problem you are experiencing is not related to point lights but with shadows. The way shadow maps. The sample only works with directional lights and changing if you change the scene size or the elements you should tweak some shadow map configuration. This is something i need to review to make it work in a more generic way. Try to disable shadow rendering and check if this works.

3) Z rotation is not implemented. I will add this to my potential todo tasks. 

Best regards.

**Comment by AndreiDarashkou** [comment]
1) Yes, I use Windows 10. And it seems that after starting any java application is creating background java process. Maybe jvm loads necessary classes once and it is normal.
2) Problem arose with appearance shadow mapping. I discover that it is normal works after disabling calculation shadowFactor (or set '1' for all cases) in scene-fragment.fs.

**Comment by lwjglgamedev** [comment]
Ok, you can use Process explorer to check if this process is created when launching the examples or not https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx

Regarding the shadow mapping problems, it's due to the fact taht you must craful tweak the paarmeters so the shado map contains your scene. I will try to modify the source code to be mor generic.
