### ISSUE TITLE
Chapter 5 | Rendering

### ISSUE THREAD

**Issue by Pichuminer** [lwjglgamedev/lwjglbook#76]
I've copied all the code from this **incredible** book, however, when I got to chapter 5 and rendering a triangle, it displays this error :
### 
[SHADER] There was a warning validating Shader code, here: Validation Failed: No vertex array object bound.

I'm checking back at the code as I post this, however, there are no errors or nothing besides this. Which is technically an error.

**Comment by lwjglgamedev** [comment]
Hi,

Thanks for your words. Did you post previoulsy the stack trace? From the email that I got it seemed that you were not able to load the shader itself. Can you check this?

Regards.

**Comment by Pichuminer** [comment]
> Hi,
> 
> Thanks for your words. Did you post previoulsy the stack trace? From the email that I got it seemed that you were not able to load the shader itself. Can you check this?
> 
> Regards.

I'm so sorry, I actually fixed that situation but now I'm receiving the error I posted now on here.

Apparently, it was my fault, however, I still haven't figured out the problem you see currently on this issue thread.
