### ISSUE TITLE
License for source code

### ISSUE THREAD

**Issue by suprafun** [lwjglgamedev/lwjglbook#8]
Thank-you so very much for taking the time to write such an informative book.

I would clarify under what license is the book source code released under ?

I am slightly confused as the book itself mentions that the license is " Attribution-ShareAlike 4.0 International (CC BY-SA 4.0) " but is this for the book material itself or is it for the source code in this GitHub project or for both the book material and the source code ?

Thank-you again

**Comment by lwjglgamedev** [comment]
Thank for your comments.

The license should be the same for both, the book and the source code. But, keep in mind that with the source code thera some resoures (textures, models, etc.) that are not created by me, and are not subject to that license. I've used them for the samples, but I'm not the author. I've tried to give proper credit on the book (If you find something missing about this, please let me know).

I should propblably state this in the source code. I'm not an expert in licenses, so it may be the most appropriate for the source code.
