### ISSUE TITLE
Streams.toList vs Streams.forEach

### ISSUE THREAD

**Issue by Speiger** [lwjglgamedev/lwjglbook#9]
o/
Love the new revision of the book and getting modern java into use.
Though I have found a inconsistency with the book.

This line specifically showed up multiple times.
https://github.com/lwjglgamedev/lwjglbook-bookcontents/blob/main/chapter-21/chapter-21.md?plain=1#L529

Where you go into stream territory and then leap out of it again to use lists instead.
While I get that using streams can be useful to filter unwanted things out, you honestly shouldn't double dip every time it seems convenient.
While it is just a small issue, you are kinda teaching a habit here.
instead of "toList" you could have used "forEach" and have gotten out slightly more performance then normal instead of iterating over every element twice that was selected.

I know this is more for tutorial reasons,
but constantly recalculating everything isn't always a good idea.
While i get this is to display how things work, a lot of new people, like me back then, don't know certain pitfalls that lie ahead.

Note that this is honestly just a "I have to itch that tick" kinda issue report/improvement suggestion, i am fully aware of that.
That's why I am also totally fine with you just closing the issue without actually addressing things.

One last thing: for this exact reason (stream point) i have written myself a library that can do stream things but with "Iterable" interfaces instead. Less overhead and same functionality and still not forced to create copies if you want to use them in things that use Iterable.

**Comment by lwjglgamedev** [comment]
Hi, yes you're right, it is not good creating many objects in a render loop. Just being lazy theret I guess. I will recheck it. I try to limit streams somehow because sometinmes code seems to be complex to read. I guess in this case it makes sense to to do a for each. Let me check it and will upload a new version. Currently working on vulkan book, so it will take me some time.

**Comment by Speiger** [comment]
Hey, wow that was a insanely quick reply.
Yeah no worry, this is like a really low issue, so don't prioritize this.
Do it when you have time :)

Also yeah, you have to juggle complexity/speed.
Which in tutorials makes sense, but it should also be acknowledged that inefficiencies are present because of a tutorial :)

**Comment by lwjglgamedev** [comment]
Just uploaded some modfications to be more consistent. In the specific case you mention, I opted for not using streams at all, the code is clean enough and lambadas do not mix weel with non final external variables.

**Comment by Speiger** [comment]
Small addendum, while reading your vulkan book, you are using streams to do forEach on arrays.
While that is totally fine, and makes the code a lot cleaner, I just want to tell you a faster/backend cleaner version is using "SplitIterators" instead.
A Stream creates a statemachine in the background and doing a task is creating a few objects and layers just to iterate over things.
A split iterator actually just performs the "forloop" you would otherwise do with a few minor initial checks that it has to do since the work can be split (parallelized).

Fun fact, streams actually create a Splititerator to base its statemachine on.

Here is the code from your GLBook.
```java
public void clean() {
    Arrays.stream(commandBuffers).forEach(CommandBuffer::cleanup);
}
```

while the SplitIterator Version would look like this:
```java
public void cleanup() {
    Arrays.spliterator(commandBuffers).forEachRemaining(CommandBuffer::cleanup);
}
```

Another thing that I just reminded myself of while writing to this point is.
Arrays.asList();
```java
public void clean() {
    Arrays.asList(commandBuffers).forEach(CommandBuffer::cleanup);
}
```
Which has the exact same performance, maybe even faster then splititerators.
But at that point we are talking nanoseconds difference.
Downside of that one is you can not use it on Primitive Types, which stream & splititerators have.

In general, unless it makes a major difference in code readability, streams should be avoided.

Small last edit performance wise:
If you are work with a headnode, performance wise it comes down to almost the same. Which you are doing, but i still would advise against streams. Since a statemachine is still created.

**Comment by lwjglgamedev** [comment]
Thanks for reporting, I've already converted some of them using the `asList` method, levaing stream creation for filtering.

**Comment by lwjglgamedev** [comment]
Closing this. If something is still missing, please reopen.
