### ISSUE TITLE
Typo in timer class, chapter 2

### ISSUE THREAD

**Issue by lucasmontec** [lwjglgamedev/lwjglbook#9]
typo in Timer class of chapter 2:
public float getEllapsedTime() {

**Comment by lwjglgamedev** [comment]
Ups. It's in chapter 2, 3......21

Thanks for the report. I will correct this as soon as possible.

**Comment by lwjglgamedev** [comment]
I've just uploaded a version that corrects that typo. 

Please close the issue if you consider this as fixed.

**Comment by lucasmontec** [comment]
Fixed ;)
