### ISSUE TITLE
Visual glitch

### ISSUE THREAD

**Issue by parpar8090** [lwjglgamedev/lwjglbook#93]
![image](https://user-images.githubusercontent.com/51650998/108009125-9c83f200-6fc7-11eb-98f5-7562f349819d.png)
Only happens when the glitched shadow is in the "sky" (where any other object exists). Also not happens when the window is in fullscreen or maximized, only when in other states.

**Comment by lwjglgamedev** [comment]
Hi,

Can you please state in which chapter you do experience this issue? If you can, provide camera settings. If you have modified the source code, please provide a link to the repository to try to replicate it.

**Comment by parpar8090** [comment]
> Hi,
> 
> Can you please state in which chapter you do experience this issue? If you can, provide camera settings. If you have modified the source code, please provide a link to the repository to try to replicate it.

I am using chapter 28, not modified

**Comment by lwjglgamedev** [comment]
Ok, but the objects rendered are different, this is not what is rendered in that chapter (so you should have modified at least that part). Could you share that part, specially the camera? Another question, is  the glitch temporary or it is permanent?

**Comment by parpar8090** [comment]
> Ok, but the objects rendered are different, this is not what is rendered in that chapter (so you should have modified at least that part). Could you share that part, specially the camera? Another question, is the glitch temporary or it is permanent?

```
public void init(Window window) throws Exception {
        renderer.init(window);

        scene = new Scene();

        Mesh[] houseMesh = StaticMeshesLoader.load("models/cube.obj", "models/house");
        GameItem house = new GameItem(houseMesh);

        scene.setGameItems(new GameItem[]{house});

        // Shadows
        scene.setRenderShadows(true);

        // Fog
        Vector3f fogColour = new Vector3f(0.5f, 0.5f, 0.5f);
        scene.setFog(new Fog(true, fogColour, 0.02f));

        // Setup  SkyBox
        float skyBoxScale = 100.0f;
        SkyBox skyBox = new SkyBox("models/skybox.obj", new Vector4f(0.65f, 0.65f, 0.65f, 1.0f));
        skyBox.setScale(skyBoxScale);
        scene.setSkyBox(skyBox);

        // Setup Lights
        setupLights();

        camera.getPosition().x = -17.0f;
        camera.getPosition().y =  17.0f;
        camera.getPosition().z = -30.0f;
        camera.getRotation().x = 20.0f;
        camera.getRotation().y = 140.f;
    }
```

**Comment by lwjglgamedev** [comment]
Thanks, I will have a look at it.

**Comment by lwjglgamedev** [comment]
I've just uploaed a fix. Let me me know if that works for you.

The problem was when resizing a window. The size of the buffer in the fog step was wrong. In any case, current code can be simplfied by just drawing 3 vertices and properly setting coordinates in the vertex buffer (no need to hang with screen size). Although this sample uses Vulkan, you can see how this can be done [here](https://github.com/lwjglgamedev/vulkanbook/tree/master/bookcontents/chapter-10).

I'm currentlt working with Vulkan but if I have some spare time I will update this chapter to simplify this.

Many thanks for pointing the issue.

**Comment by lwjglgamedev** [comment]
Closing the issue. If it persists, please reopen.
