### ISSUE TITLE
Why do I have 10 errors in my pom.xml at the begining?

### ISSUE THREAD

**Issue by Sergio0Sergio** [lwjglgamedev/lwjglbook#95]

**Comment by lwjglgamedev** [comment]
Hi, 
Can you please provide more info about the error you got? Which chapter, what command did you exeucte, the error messages that you are getting, etc.

**Comment by lwjglgamedev** [comment]
I'm closing this issue. Honestly, I don't know how I can help on this without more information. If you are able to provide this, please reopen.
