### ISSUE TITLE
Code snippet incorrect in Chapter 2

### ISSUE THREAD

**Issue by deitrix** [lwjglgamedev/lwjglbook#99]
The delta timing code snippet in chapter 2 is incorrect. Variables `loopStartTime` and `current` used interchangeably.

```java
double secsPerUpdate = 1.0d / 30.0d;
double previous = getTime();
double steps = 0.0;
while (true) {
  double loopStartTime = getTime();
  double elapsed = loopStartTime - previous;
  previous = current;
  steps += elapsed;

  handleInput();

  while (steps >= secsPerUpdate) {
    updateGameState();
    steps -= secsPerUpdate;
  }

  render();
  sync(current);
}
```

**Comment by lwjglgamedev** [comment]
Thanos, I will hace a look at it. (It will take some days)

**Comment by lwjglgamedev** [comment]
Hi, 

Sorry for the late response. I've checked the chapter contents and I'not able to see that fragment. Are you sure you are viewieng the last version?

**Comment by deitrix** [comment]
Looks like I may potentially be looking at an old version of the book, apologies:

https://lwjglgamedev.gitbooks.io/3d-game-development-with-lwjgl/content/chapter02/chapter2.html

**Comment by lwjglgamedev** [comment]
No problem. Thanks for clarifying this.
